# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d974428b2c6eefd721756e41c2915f901420efa841d800e3bdf90ba6c82aa88f157d3b257dd2daa67bc6d78ccd00b78b4a4d2abece5921f566079e7d9405aaef

test:
  secret_key_base: eaf9a3ae20c48cd8c1ebc16bd7eb625d8a84612f386f928a09acd085e2c1296938d7c26bee428357f8a32d2f33a3c001a72704758b86002f501eabfbb46e942b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
